Repository Icinga/icinga-powershell-framework, pull requests merged in 2020-10, with the labels that each got.

#130 Bugfix: Fix crash on background service execution caused by missing Perf Data cache
  doc/31-Changelog.md
  icinga-powershell-framework.psm1
Labels: Crash

#135 Doc: Update roadmap with new topics and releases
  doc/90-Roadmap.md
Labels: Documentation

#136 Feature: Adds support to ignore empty check packages
  doc/31-Changelog.md
  doc/developerguide/02-New-IcingaCheckPackage.md
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
Labels: Enhancement

#137 Feature: Compare current time with DateTime Object
  doc/31-Changelog.md
  lib/core/tools/Compare-IcingaUnixTimeWithDateTime.psm1
Labels: Enhancement

#138 Bugfix: Fixing value overflow on Convert-Bytes Cmdlet
  doc/31-Changelog.md
  lib/core/tools/Convert-Bytes.psm1
Labels: Bug

#139 Feature: Add Cmdlet to open Icinga Shell as different user
  doc/31-Changelog.md
  icinga-powershell-framework.psd1
  icinga-powershell-framework.psm1
Labels: Enhancement
