Repository Icinga/icinga-powershell-framework, pull requests merged in 2020-11, with the labels that each got.

#140 Fix: Version fetching for not loaded modules is impossible
  doc/31-Changelog.md
  lib/core/framework/Get-IcingaPowerShellModuleVersion.psm1
Labels: Bug

#141 Feature: Add generic Cmdlet to convert Icinga Thresholds
  doc/31-Changelog.md
  lib/core/tools/Convert-Bytes.psm1
  lib/core/tools/Convert-IcingaPluginThresholds.psm1
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Labels: Enhancement

#143 Disable OnSameLine & don't check space before open brace
  PSScriptAnalyzerSettings.psd1
  doc/31-Changelog.md
Labels: Bug

#134 Check whether or not WMI class exists
  doc/31-Changelog.md
  lib/core/framework/Test-IcingaWindowsInformation.psm1
  lib/core/tools/Test-IcingaBinaryOperator.psm1
  lib/icinga/enums/Test-IcingaWindowsInfoEnums.psm1
  lib/icinga/exception/Get-IcingaLastExceptionId.psm1
Labels: Enhancement

#60 Bugfix: Handle multiple network interfaces on discovery and add support for Windows 2008 R2
  doc/31-Changelog.md
  lib/core/tools/Get-IcingaNetworkInterface.psm1
  lib/core/tools/Get-IcingaNetworkRoute.psm1
Labels: Bug, Enhancement

#145 Doc: Adds help for certificate installation Cmdlet
  lib/core/icingaagent/installer/Install-IcingaAgentCertificates.psm1
Labels: Documentation

#146 Fix: Icinga API being disabled after successfull certificate installation
  doc/31-Changelog.md
  lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
Labels: Bug

#147 Fix: SSL creation on reconfigure might fail if naming changed from upper/lower case
  doc/31-Changelog.md
  lib/core/icingaagent/installer/Install-IcingaAgentCertificates.psm1
Labels: Bug

#149 Feature: Adds support to add/remove/test Wmi permissions
  doc/31-Changelog.md
  lib/core/tools/Get-IcingaUserSID.psm1
  lib/core/tools/Split-IcingaUserDomain.psm1
  lib/wmi/Add-IcingaWmiPermissions.psm1
  lib/wmi/Get-IcingaWindowsInformation.psm1
  lib/wmi/Get-IcingaWmiSecurityData.psm1
  lib/wmi/Icinga_WBEM_Security.psm1
  lib/wmi/New-IcingaWmiPermissionMask.psm1
  lib/wmi/Remove-IcingaWmiPermissions.psm1
  lib/wmi/Test-IcingaWindowsInformation.psm1
  lib/wmi/Test-IcingaWmiPermissions.psm1
Labels: Enhancement

#151 Doc: Adds first knowledge base entries
  README.md
  doc/10-Knowledge-Base.md
  doc/images/04_knowledgebase/IWKB000002/01_Plugin_Output_Error.png
  doc/images/04_knowledgebase/IWKB000002/02_Director_Config.png
  doc/images/04_knowledgebase/IWKB000002/03_Fixed_Output.png
  doc/knowledgebase/IWKB000001.md
  doc/knowledgebase/IWKB000002.md
Labels: Documentation

#152 Fix: Array handling for ValidateSet and array rendering for config generator
  doc/31-Changelog.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Bug

#142 Experimental: Adds code caching for faster framework loading
  doc/31-Changelog.md
  icinga-powershell-framework.psd1
  icinga-powershell-framework.psm1
  lib/config/Read-IcingaPowerShellConfig.psm1
  lib/core/framework/Disable-IcingaFrameworkCodeCache.psm1
  lib/core/framework/Enable-IcingaFrameworkCodeCache.psm1
  lib/core/framework/Get-IcingaFrameworkCodeCache.psm1
  lib/core/framework/Install-IcingaFrameworkUpdate.psm1
Labels: Enhancement

#154 Doc: Add description on how to uninstall Icinga Agent and add KB for issues
  doc/06-Framework-Usage.md
  doc/10-Knowledge-Base.md
  doc/frameworkusage/34-Uninstall-Icinga-Agent.md
  doc/knowledgebase/IWKB000003.md
Labels: Documentation

#155 Feature: Add debug output for Get-IcingaWindowsInformation calls to EventLog
  doc/31-Changelog.md
  lib/wmi/Get-IcingaWindowsInformation.psm1
Labels: Enhancement

#156 Feature: Allow sharing of local variables with Icinga Shell
  doc/31-Changelog.md
  icinga-powershell-framework.psm1
Labels: Enhancement

#157 Feature: Add Proxy Server support for web calls
  doc/06-Framework-Usage.md
  doc/31-Changelog.md
  doc/frameworkusage/02-Enable-Proxy-Server.md
  lib/apis/Get-IcingaDirectorSelfServiceConfig.psm1
  lib/apis/Get-IcingaDirectorSelfServiceTicket.psm1
  lib/apis/Register-IcingaDirectorSelfServiceHost.psm1
  lib/core/framework/Get-IcingaFrameworkServiceBinary.psm1
  lib/core/framework/Get-IcingaPowerShellModuleArchive.psm1
  lib/core/icingaagent/getters/Get-IcingaAgentMSIPackage.psm1
  lib/core/icingaagent/installer/Install-IcingaAgentCertificates.psm1
  lib/web/Disable-IcingaProgressPreference.psm1
  lib/web/Get-IcingaFrameworkProxyServer.psm1
  lib/web/Invoke-IcingaWebRequest.psm1
  lib/web/Set-IcingaFrameworkProxyServer.psm1
  lib/web/Set-IcingaTLSVersion.psm1
  lib/webserver/Close-IcingaTCPConnection.psm1
  lib/webserver/Close-IcingaTCPSocket.psm1
  lib/webserver/Convert-Base64ToCredentials.psm1
  lib/webserver/ConvertTo-IcingaX509Certificate.psm1
  lib/webserver/Disable-IcingaUntrustedCertificateValidation.psm1
  lib/webserver/Enable-IcingaUntrustedCertificateValidation.psm1
  lib/webserver/Get-IcingaRESTHeaderValue.psm1
  lib/webserver/Get-IcingaRESTPathElement.psm1
  lib/webserver/Get-IcingaSSLCertForSocket.psm1
  lib/webserver/Get-IcingaTCPClientRemoteEndpoint.psm1
  lib/webserver/Icinga_HTTPResponse_Enums.psm1
  lib/webserver/New-IcingaSSLStream.psm1
  lib/webserver/New-IcingaTCPClient.psm1
  lib/webserver/New-IcingaTCPClientRESTMessage.psm1
  lib/webserver/New-IcingaTCPSocket.psm1
  lib/webserver/Open-IcingaTCPClientConnection.psm1
  lib/webserver/Read-IcingaRESTMessage.psm1
  lib/webserver/Read-IcingaTCPStream.psm1
  lib/webserver/Send-IcingaTCPClientMessage.psm1
  lib/webserver/Send-IcingaWebAuthMessage.psm1
  lib/webserver/Test-IcingaRESTCredentials.psm1
Labels: Enhancement

#158 Doc: Updates WMI KB for Winmgmt service restart
  doc/knowledgebase/IWKB000001.md
Labels: Documentation

#159 Fix: Fixes crash during update due to code cache feature
  doc/31-Changelog.md
  lib/core/framework/Install-IcingaFrameworkUpdate.psm1
Labels: Crash

#160 Fix: Instaling PowerShell components fails for release branch
  lib/core/framework/Get-IcingaPowerShellModuleArchive.psm1
Labels: Bug

#161 Doc: Adds upgrading notes for plugins and kickstart for v1.3.0
  doc/30-upgrading-framework.md
Labels: Documentation

#162 Feature: Adds error on config generator for 64 digit args
  doc/31-Changelog.md
  doc/icingaintegration/01-Director-Baskets.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Enhancement

#164 Feature: Adds exit to Windows Terminal integration to close shell on exit
  doc/31-Changelog.md
  doc/icingaintegration/50-Windows-Terminal.md
Labels: Enhancement

#153 Feature: Adds support for adding a knowledge base id to exceptions
  doc/31-Changelog.md
  lib/icinga/exception/Exit-IcingaThrowException.psm1
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Labels: Enhancement

#163 Feature: Adds native Icinga config generation support and adds simple publish command
  doc/05-Icinga-Integration.md
  doc/31-Changelog.md
  doc/icingaintegration/04-Icinga-Config.md
  lib/core/framework/Publish-IcingaPluginConfiguration.psm1
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Enhancement

#165 Fix: Fixes fetching for Icinga Agent certificate for REST-Api daemon on upper/lower case hostname mismatch
  doc/31-Changelog.md
  lib/core/icingaagent/getters/Get-IcingaAgentHostCertificate.psm1
Labels: Bug

#166 Fix: Fixes release fetching of Agent with correct comparison and proper support for local sources
  doc/31-Changelog.md
  lib/core/icingaagent/getters/Get-IcingaAgentMSIPackage.psm1
Labels: Enhancement

#167 Fix: Fixes error while writing EventLog entries with too large message size
  doc/31-Changelog.md
  lib/core/logging/Write-IcingaEventMessage.psm1
Labels: Bug

#168 Feature: Adds support for new Director SelfService config arguments
  doc/31-Changelog.md
  lib/core/icingaagent/misc/Convert-IcingaDirectorSelfServiceArguments.psm1
  lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
Labels: Enhancement

#169 Fix: Small fix for Icinga .conf generation
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Bug

#170 Doc: Extends KB for execution policy and path
  doc/10-Knowledge-Base.md
  doc/knowledgebase/IWKB000004.md
  doc/knowledgebase/IWKB000005.md
Labels: Documentation

#171 Docs: Adds Agent install/uninstall description
  doc/06-Framework-Usage.md
  doc/frameworkusage/35-Install-Update-Icinga-Agent.md
Labels: Documentation

#172 Doc: Adds installation wizard guide and overview
  doc/06-Framework-Usage.md
  doc/frameworkusage/03-Install-Wizard-Guide.md
  lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
Labels: Documentation

#173 Fix: Fixes Windows Updates permission exception; Add KB
  doc/10-Knowledge-Base.md
  doc/knowledgebase/IWKB000006.md
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Labels: Documentation

#174 Fix: Fixes exception output not properly constructed
  lib/icinga/exception/Exit-IcingaThrowException.psm1
Labels: Bug

#175 Doc: Adds UI configuration description for path environment variable
  doc/knowledgebase/IWKB000005.md
Labels: Documentation

#176 Doc: Updates Docs, Roadmap and Release Dates for v1.3.0
  doc/01-Introduction.md
  doc/30-upgrading-framework.md
  doc/31-Changelog.md
  doc/90-Roadmap.md
Labels: Documentation

#177 Fix: Allow usage for domain accounts for wmi permissions without being locally known
  doc/31-Changelog.md
  lib/wmi/Get-IcingaWmiSecurityData.psm1
Labels: Bug

#178 Feature: Updates version to 1.4.0
  doc/30-upgrading-framework.md
  doc/31-Changelog.md
  icinga-powershell-framework.psd1
Labels: Enhancement
