Repository Icinga/icinga-powershell-framework, pull requests merged in 2020-08, with the labels that each got.

#107 Feature: Improve Performance Counter docs and functionality
  doc/31-Changelog.md
  lib/core/perfcounter/Add-IcingaPerformanceCounterCache.psm1
  lib/core/perfcounter/Get-IcingaPerformanceCounterCacheItem.psm1
  lib/core/perfcounter/Icinga_GlobalPerfCounterCache.psm1
  lib/core/perfcounter/New-IcingaPerformanceCounter.psm1
  lib/core/perfcounter/New-IcingaPerformanceCounterArray.psm1
  lib/core/perfcounter/New-IcingaPerformanceCounterCache.psm1
  lib/core/perfcounter/New-IcingaPerformanceCounterNullObject.psm1
  lib/core/perfcounter/New-IcingaPerformanceCounterObject.psm1
  lib/core/perfcounter/New-IcingaPerformanceCounterResult.psm1
  lib/core/perfcounter/New-IcingaPerformanceCounterStructure.psm1
  lib/core/perfcounter/Show-IcingaPerformanceCounterCategories.psm1
  lib/core/perfcounter/Show-IcingaPerformanceCounters.psm1
  lib/core/perfcounter/Test-IcingaPerformanceCounterCategory.psm1
Labels: Documentation, Enhancement

#109 Documentation: Improve introduction and fix spelling errors
  doc/01-Introduction.md
  doc/02-Installation.md
  doc/images/02_icons/framework.png
  doc/images/02_icons/hyperv.png
  doc/images/02_icons/inventory.png
  doc/images/02_icons/kickstart.png
  doc/images/02_icons/mssql.png
  doc/images/02_icons/plugins.png
  doc/images/02_icons/restapi.png
  doc/installation/02-Manual-Installation.md
  doc/installation/03-PowerShell-Gallery-Installation.md
  doc/installation/04-Icinga-Agent-Wizard.md
Labels: Documentation

#110 Documentation: Add roadmap for Icinga for Windows
  doc/90-Roadmap.md
Labels: Documentation

#112 Improves msg for permssion error on CIM/WMI access
  doc/31-Changelog.md
  lib/core/framework/Get-IcingaWindowsInformation.psm1
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Labels: Enhancement

#115 Feature: Adds exception for missing Perf Counter category
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Labels: Enhancement

#118 Adds exception message for Windows Updates
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Labels: Enhancement

#119 Feature: Adds MSSQL connector
  lib/icinga/exception/Exit-IcingaThrowException.psm1
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
  lib/mssql/Close-IcingaMSSQLConnection.psm1
  lib/mssql/New-IcingaMSSQLCommand.psm1
  lib/mssql/Open-IcingaMSSQLConnection.psm1
  lib/mssql/Send-IcingaMSSQLCommand.psm1
Labels: Enhancement

#125 Adds Windows Terminal integration
  doc/05-Icinga-Integration.md
  doc/31-Changelog.md
  doc/90-Roadmap.md
  doc/icingaintegration/50-Windows-Terminal.md
  doc/images/03_windows_terminal/icinga_shell.png
  doc/images/03_windows_terminal/icingawhite.png
  icinga-powershell-framework.psm1
  lib/core/logging/Write-IcingaConsoleWarning.psm1
Labels: Documentation, Enhancement
