Repository Icinga/icinga-powershell-framework, pull requests merged in 2021-06, with the labels that each got.

#272 Fix: Exception on time conversion in case first letter matches time metric
  doc/31-Changelog.md
  lib/core/tools/ConvertFrom-TimeSpan.psm1
  lib/core/tools/ConvertTo-Seconds.psm1
Labels: Bug

#270 Fix: Framework root folder lookup
  doc/31-Changelog.md
  icinga-powershell-framework.psd1
  icinga-powershell-framework.psm1
  lib/core/framework/Get-IcingaPowerShellModuleArchive.psm1
  lib/core/framework/Publish-IcingaPluginConfiguration.psm1
  lib/core/framework/Uninstall-IcingaForWindows.psm1
  lib/core/framework/Uninstall-IcingaFrameworkComponent.psm1
  lib/core/installer/menu/manage/framework/backgrounddaemons/Show-IcingaForWindowsManagementConsoleRegisterBackgroundDaemons.psm1
  lib/core/tools/Write-IcingaConsoleHeader.psm1
Labels: Bug

#275 Docs: Adds PerfLib error IWKB000008
  doc/10-Knowledge-Base.md
  doc/images/04_knowledgebase/IWKB000008/01_EventLog_Error.png
  doc/knowledgebase/IWKB000008.md
Labels: Documentation

#278 Docs: Update 04-Icinga-Agent-Wizard.md
  doc/installation/04-Icinga-Agent-Wizard.md
Labels: Documentation

#280 Docs: fix typo on manual integration page 02-Manual-Integration.md
  doc/06-Framework-Usage.md
  doc/icingaintegration/02-Manual-Integration.md
Labels: Documentation

#283 Fix: String builder creation on older windows machines
  doc/31-Changelog.md
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
Labels: Bug

#277 Fix: Input value decimal conversion
  doc/31-Changelog.md
  lib/core/tools/Test-IcingaDecimal.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Labels: Bug

#286 Fix: Plain Icinga config generation
  doc/31-Changelog.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Bug

#287 Fix: Crash on creation of default threshold values
  doc/31-Changelog.md
  lib/core/tools/ConvertTo-Seconds.psm1
Labels: Crash

#293 Fix: NULL exception on REST message
  doc/31-Changelog.md
  lib/webserver/Read-IcingaRESTMessage.psm1
Labels: Crash
