Repository Icinga/icinga-powershell-framework, pull requests merged in 2021-05, with the labels that each got.

#239 Feature: Hide SecureString CustomFields input in Icinga Director
  doc/30-upgrading-framework.md
  doc/31-Changelog.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Enhancement

#240 Fix: Adds missing attributes for services
  doc/31-Changelog.md
  lib/core/tools/Get-IcingaServices.psm1
Labels: Enhancement

#241 Feature: Force new TLS version for REST
  doc/31-Changelog.md
  icinga-powershell-framework.psd1
  lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
Labels: Enhancement

#233 Feature: Suppress other messages then plugin output
  doc/31-Changelog.md
  icinga-powershell-framework.psm1
  lib/icinga/plugin/Write-IcingaPluginOutput.psm1
Labels: Enhancement

#248 Feature: Improve test if Performance Counter category exist
  doc/31-Changelog.md
  lib/core/perfcounter/Test-IcingaPerformanceCounterCategory.psm1
Labels: Enhancement

#252 Feature: Inform the user if plugins are executed which are not meeting dependency requirements
  doc/31-Changelog.md
  lib/icinga/exception/Exit-IcingaPluginNotInstalled.psm1
Labels: Enhancement

#254 Bugfix: Make exception enums not plugin specific
  lib/icinga/enums/Test-IcingaWindowsInfoEnums.psm1
Labels: Enhancement

#236 Feature: Stop Icinga Agent during Framework upgrade
  doc/31-Changelog.md
  lib/core/framework/Install-IcingaFrameworkUpdate.psm1
Labels: Enhancement

#245 Fix loading certificate from .pfx file
  lib/webserver/Get-IcingaSSLCertForSocket.psm1
Labels: Bug

#256 Fix: Self Service for removed hosts/keys inside Icinga Director
  doc/31-Changelog.md
  lib/core/icingaagent/misc/Start-IcingaAgentDirectorWizard.psm1
Labels: Bug

#247 Feature: Re-Write execution of checks
  doc/developerguide/01-New-IcingaCheck.md
  doc/developerguide/02-New-IcingaCheckPackage.md
  lib/core/tools/Convert-Bytes.psm1
  lib/core/tools/Convert-IcingaCheckArgumentToPSObject.psm1
  lib/core/tools/Convert-IcingaPluginValueToString.psm1
  lib/core/tools/ConvertFrom-Percent.psm1
  lib/core/tools/ConvertFrom-TimeSpan.psm1
  lib/core/tools/ConvertTo-BytesNextUnit.psm1
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
  lib/core/tools/Get-IcingaNextUnitIteration.psm1
  lib/help/help/Get-IcingaHelpThresholds.psm1
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
  lib/icinga/plugin/ConvertTo-IcingaPluginOutputTranslation.psm1
  lib/icinga/plugin/New-IcingaCheck.psm1
  lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
  lib/icinga/plugin/New-IcingaCheckResult.psm1
  lib/icinga/plugin/New-IcingaPerformanceDataEntry.psm1
  lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
Labels: Enhancement

#249 Feature: Rewrite exception handler
  doc/31-Changelog.md
  lib/icinga/exception/Exit-IcingaThrowException.psm1
Labels: Enhancement

#255 Fix: Array handling on log analyser and adds timestamp to output
  lib/core/tools/Show-IcingaEventLogAnalysis.psm1
Labels: Bug, Enhancement

#257 Fix: Unhandled units might cause exception on maximum compare
  lib/core/tools/Convert-IcingaPluginThresholds.psm1
Labels: Bug

#258 Fix: Header summary should not include hidden packages/elements
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
Labels: Bug

#259 Fix: Missing rounding for time span values
  lib/core/tools/ConvertFrom-TimeSpan.psm1
Labels: Enhancement

#260 Fix: Numeric converison to comparing thresholds is incorrect
  lib/core/tools/Convert-IcingaPluginThresholds.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Labels: Bug

#261 Fix: Performance Data was not written for checks which were not compared to a threshold
  lib/icinga/plugin/New-IcingaCheck.psm1
Labels: Bug

#262 Fix: Input value from check objects was sometimes not properly converted to decimal
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Labels: Bug

#263 Fix: Removes colon at the end of the packlage summary
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
Labels: Bug

#264 Feature: Adds first handling for Framework link speeds
  doc/31-Changelog.md
  lib/core/tools/Convert-IcingaPluginValueToString.psm1
  lib/core/tools/Get-IcingaNetworkInterfaceUnits.psm1
  lib/icinga/enums/Icinga_IcingaEnums.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Labels: Enhancement

#265 Fix: Test-Numeric allows no negative value and TimeSpan conversion ignores negatives and microseconds
  doc/31-Changelog.md
  lib/core/tools/Convert-IcingaPluginThresholds.psm1
  lib/core/tools/ConvertFrom-TimeSpan.psm1
  lib/core/tools/Test-Numeric.psm1
Labels: Bug, Enhancement

#266 Fix: Perf data should only add maximum if it was set before
  lib/icinga/plugin/New-IcingaCheck.psm1
Labels: Bug

#267 Fix: Double colon is added, even if check name already contains it
  lib/icinga/plugin/New-IcingaCheck.psm1
Labels: Enhancement

#268 Feature: Ensure numbers are printed as numeric with . instead of ','
  lib/core/tools/Convert-IcingaPluginValueToString.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Labels: Enhancement

#269 Fix: Unhandled exception on Icinga Cache
  doc/31-Changelog.md
  lib/core/cache/Set-IcingaCacheData.psm1
Labels: Bug

#271 Fix: StackOverflowException on invalid ThresholdInterval
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
  lib/icinga/plugin/New-IcingaCheck.psm1
  lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
Labels: Crash
