Repository Icinga/icinga-powershell-framework, pull requests merged in 2021-01, with the labels that each got.

#188 Fix: Removes hardcoded global zones
  doc/31-Changelog.md
  lib/core/icingaagent/writers/Write-IcingaAgentZonesConfig.psm1
Labels: Bug

#189 Fix: Wrong user group for Performance Counter permissions
  doc/31-Changelog.md
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Labels: Documentation

#193 Feature: Add optional support for adding milliseconds to Get-IcingaUnixTime
  doc/31-Changelog.md
  lib/core/tools/Get-IcingaUnixTime.psm1
Labels: Enhancement

#187 Fix backslashes in the url path causes an error
  doc/31-Changelog.md
  lib/core/framework/Get-IcingaFrameworkServiceBinary.psm1
Labels: Bug

#195 Fix: Agent installer crash on package lookup with different files in directory
  doc/31-Changelog.md
  lib/core/icingaagent/getters/Get-IcingaAgentMSIPackage.psm1
Labels: Bug

#197 Fix: Disables PowerShell Progress bar while using Icinga for Windows
  doc/31-Changelog.md
  icinga-powershell-framework.psm1
Labels: Bug

#192 Fix: Prefer startup type of services fetching over WMI instead of Get-Services
  doc/31-Changelog.md
  lib/core/tools/Get-IcingaServices.psm1
  lib/icinga/enums/Icinga_IcingaEnums.psm1
Labels: Bug
