Repository Icinga/icinga-powershell-framework, pull requests merged in 2022-08, with the labels that each got.

#536 Feature: Adds function for easier include/exclude filtering
  doc/100-General/10-Changelog.md
  lib/core/tools/Test-IcingaArrayFilter.psm1
Labels: Enhancement, cla/signed

#540 Docs: Fixes doc for custom repo example installation
  doc/110-Installation/01-Getting-Started.md
Labels: Documentation, cla/signed

#541 Fix: Uninstaller removal errors by improving location handling
  doc/100-General/10-Changelog.md
  icinga-powershell-framework.psm1
  lib/core/framework/Uninstall-IcingaForWindows.psm1
  lib/core/installer/Install-Icinga.psm1
  lib/core/repository/Uninstall-IcingaComponent.psm1
Labels: Bug, cla/signed

#542 Fix: Null-value exception on missing background daemons
  doc/100-General/10-Changelog.md
  lib/daemon/Get-IcingaBackgroundDaemons.psm1
Labels: Bug, cla/signed

#543 Fix: icinga command always resetting cache
  icinga-powershell-framework.psm1
Labels: Bug, cla/signed

#534 Fix the creation of powershell arrays in Icinga2 configuration
  doc/100-General/10-Changelog.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Enhancement, cla/signed

#473 Fix: Adds DSL parser to string arguments to fix whitespace and $ escaping
  doc/100-General/10-Changelog.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Bug, Enhancement, cla/signed

#482 Fix: Encoding problems with special chars or German umlauts
  doc/100-General/10-Changelog.md
  icinga-powershell-framework.psm1
  lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
  lib/core/icingaagent/readers/Read-IcingaAgentDebugLogFile.psm1
  lib/core/icingaagent/readers/Read-IcingaAgentLogFile.psm1
  lib/core/tools/ConvertTo-IcingaPowerShellArguments.psm1
  lib/core/tools/ConvertTo-IcingaUTF8Value.psm1
  lib/icinga/plugin/Exit-IcingaExecutePlugin.psm1
Labels: Bug, cla/signed

#547 Docs: Fixes wrong argument on Install-Icinga from file
  doc/110-Installation/04-Installation-Templates.md
  lib/core/installer/menu/installation/general/InstallationFileExport.psm1
Labels: Documentation, cla/signed

#548 Fix: RemoteSouce being cleared during Update-IcingaRepository
  doc/100-General/10-Changelog.md
  lib/core/repository/Update-IcingaRepository.psm1
Labels: Bug, cla/signed

#549 Fix: Remote Sync clears RemoteSource
  lib/core/repository/Update-IcingaRepository.psm1
Labels: Bug, cla/signed

#551 Fix: Argument does not support percent unit error messagae
  doc/100-General/10-Changelog.md
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Labels: Bug, cla/signed

#552 Fix: Cache file encoding read/write
  cache/framework_cache.psm1
  doc/100-General/01-Upgrading.md
  doc/100-General/10-Changelog.md
  icinga-powershell-framework.psm1
Labels: Crash, cla/signed

#554 Fix: Automated Icinga Director installation for custom hostname
  doc/100-General/10-Changelog.md
  lib/core/installer/menu/installation/director/DirectorTemplate.psm1
Labels: Bug, cla/signed

#526 Feature: Rewrite PerfData Labels for multi output
  doc/100-General/10-Changelog.md
  lib/core/framework/Get-IcingaCheckSchedulerPerfData.psm1
  lib/core/framework/Get-IcingaCheckSchedulerPluginOutput.psm1
  lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
  lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
  lib/core/perfcounter/Get-IcingaPerformanceCounterDetails.psm1
  lib/core/tools/ConvertTo-IcingaNumericTimeIndex.psm1
  lib/core/tools/Format-IcingaPerfDataLabel.psm1
  lib/daemons/ServiceCheckDaemon/task/Add-IcingaServiceCheckTask.psm1
  lib/daemons/ServiceCheckDaemon/tools/New-IcingaServiceCheckDaemonEnvironment.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
  lib/icinga/plugin/New-IcingaCheck.psm1
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
  lib/icinga/plugin/New-IcingaCheckResult.psm1
  lib/icinga/plugin/New-IcingaPerformanceDataEntry.psm1
  lib/icinga/plugin/Write-IcingaPluginOutput.psm1
  lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
Labels: Enhancement, cla/signed

#550 Fix: Negative thresholds interpreted as argument
  doc/100-General/10-Changelog.md
  lib/core/tools/ConvertTo-IcingaPowerShellArguments.psm1
  lib/icinga/plugin/Exit-IcingaExecutePlugin.psm1
Labels: Bug, cla/signed

#556 Fix: Certificate folder not present on first installation
  certificate/.gitkeep
  doc/100-General/10-Changelog.md
Labels: Bug, cla/signed

#557 Fix: Byte unit Icinga threshold exception
  lib/core/tools/Convert-Bytes.psm1
Labels: Crash, cla/signed

#559 Docs: Extends docs for upgrading to v1.10.0 and adds KB entry
  doc/100-General/01-Upgrading.md
  doc/300-Knowledge-Base.md
  doc/images/04_knowledgebase/IWKB000014/01_framework_cache_exception.png
  doc/knowledgebase/IWKB000014.md
Labels: Documentation, cla/signed

#561 Doc: Updates Grafana installation docs to latest state
  doc/110-Installation/40-Grafana-Integration.md
  doc/images/05_installation/01_grafana/03_example_overview.png
  doc/images/05_installation/01_grafana/04_save_icon.png
  doc/images/05_installation/01_grafana/05_save_dashboard.png
Labels: Documentation, cla/signed

#560 Feature: Improves IMC update and uninstall handling for Framework
  doc/100-General/10-Changelog.md
  icinga-powershell-framework.psm1
  lib/core/framework/Uninstall-IcingaForWindows.psm1
  lib/core/installer/Install-Icinga.psm1
  lib/core/installer/tools/SetCloseIMC.psm1
  lib/core/installer/tools/SetUpdatingIMC.psm1
  lib/core/installer/tools/TestUpdatingIMC.psm1
  lib/core/repository/Install-IcingaComponent.psm1
Labels: Enhancement, cla/signed

#562 Fix: PerfData writer in JEA context without REST-Api
  doc/100-General/10-Changelog.md
  lib/icinga/plugin/Write-IcingaPluginResult.psm1
Labels: Bug, cla/signed

#564 Fix: SecureString arguments not working with REST-Api
  doc/100-General/10-Changelog.md
  lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
  lib/daemons/modules/ApiChecks/Invoke-IcingaApiChecksRESTCall.psm1
Labels: Bug, cla/signed

#565 Feature: Improve cache file writer with more robust handling
  doc/100-General/10-Changelog.md
  lib/core/cache/Copy-IcingaCacheTempFile.psm1
  lib/core/cache/Get-IcingaCacheData.psm1
  lib/core/cache/Set-IcingaCacheData.psm1
  lib/core/cache/Test-IcingaCacheDataTempFile.psm1
  lib/core/logging/Icinga_EventLog_Enums.psm1
Labels: Bug, cla/signed

#566 Fix: Useless testing for directories if agent is not installed
  doc/100-General/10-Changelog.md
  lib/core/icingaagent/tests/Test-IcingaAgent.psm1
Labels: Bug, cla/signed

#567 Fix: Missing permission update for certificate directory
  lib/core/icingaagent/setters/Set-IcingaUserPermissions.psm1
Labels: Bug, cla/signed

#568 Fix: Misleading SID error during uninstallation
  doc/100-General/10-Changelog.md
  lib/core/windows/Uninstall-IcingaServiceUser.psm1
Labels: Bug, cla/signed

#569 Feature: Adds filtering options for EventLog parser
  doc/100-General/10-Changelog.md
  lib/core/framework/Read-IcingaForWindowsLog.psm1
  lib/core/framework/Read-IcingaWindowsEventLog.psm1
  lib/core/icingaagent/readers/Read-IcingaAgentLogFile.psm1
Labels: Enhancement, cla/signed

#570 Deprecated: Start-IcingaAgentInstallWizard installation method
  doc/100-General/10-Changelog.md
  lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
Labels: Enhancement, cla/signed

#502 Fix/hostname override for old installer
  doc/100-General/10-Changelog.md
  lib/core/icingaagent/misc/Start-IcingaAgentDirectorWizard.psm1
  lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
Labels: Enhancement, cla/signed

#571 Fix: StackTrace in plugin output, when plugin is not installed
  lib/core/tools/ConvertTo-IcingaPowerShellArguments.psm1
Labels: Bug, cla/signed
