Repository Icinga/icinga-powershell-framework, pull requests merged in 2022-05, with the labels that each got.

#512 Fix Unregister Background Daemons example
  doc/110-Installation/05-Background-Daemons.md
Labels: cla/signed

#519 Fix: Missing loading for Icinga for Windows modules
  doc/100-General/10-Changelog.md
  icinga-powershell-framework.psm1
Labels: Bug, cla/signed

#520 Fix: Missing component import func on dev tools
  doc/100-General/10-Changelog.md
  lib/core/dev/New-IcingaForWindowsComponent.psm1
Labels: Bug, cla/signed

#521 Feature: Adds support for service recovery
  doc/100-General/10-Changelog.md
  lib/core/installer/Start-IcingaForWindowsInstallation.psm1
  lib/core/installer/menu/installation/AdvancedEntries.psm1
  lib/core/installer/menu/installation/framework/ServiceRecovery.psm1
  lib/core/installer/menu/manage/settings/services/ManageServices.psm1
  lib/core/windows/Disable-IcingaServiceRecovery.psm1
  lib/core/windows/Enable-IcingaServiceRecovery.psm1
Labels: Enhancement, cla/signed

#527 Feature: Adds developer mode for components
  icinga-powershell-framework.psm1
  templates/compilation.psm1.template
Labels: Enhancement, cla/signed
