Repository Icinga/icinga-powershell-framework, pull requests merged in 2022-03, with the labels that each got.

#490 Fix: Uninstaller for service component not working
  doc/100-General/10-Changelog.md
  lib/core/repository/Uninstall-IcingaComponent.psm1
Labels: Bug

#493 Doc: REST-Api section doc update
  doc/110-Installation/30-API-Check-Forwarder.md
Labels: Documentation, cla/signed

#495 Feature: Check Icinga Agent certificate sign status
  doc/100-General/10-Changelog.md
  doc/300-Knowledge-Base.md
  doc/images/04_knowledgebase/IWKB000013/01_Cert_Not_Signed.png
  doc/knowledgebase/IWKB000013.md
  lib/core/icingaagent/getters/Get-IcingaAgentHostCertificate.psm1
  lib/core/logging/Icinga_EventLog_Enums.psm1
Labels: Enhancement, cla/signed

#484 Fix: REST-Api SSL certificate lookup on custom hostname or domain/dns domain mismatch
  doc/100-General/10-Changelog.md
  lib/core/icingaagent/getters/Get-IcingaAgentHostCertificate.psm1
  lib/core/icingaagent/getters/Get-IcingaHostname.psm1
  lib/webserver/Get-IcingaSSLCertForSocket.psm1
Labels: Bug, cla/signed

#496 Fix: Improves REST-Api default timeout
  doc/100-General/10-Changelog.md
  lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
  lib/daemons/RestAPI/daemon/Start-IcingaWindowsRESTApi.psm1
Labels: Enhancement, cla/signed

#498 Feature: Add thread queuing optimisation and frozen thread detection
  doc/100-General/10-Changelog.md
  lib/core/framework/New-IcingaEnvironmentVariable.psm1
  lib/core/logging/Icinga_EventLog_Enums.psm1
  lib/core/thread/New-IcingaThreadInstance.psm1
  lib/core/thread/Remove-IcingaThread.psm1
  lib/core/thread/Set-IcingaEnvironmentThreadName.psm1
  lib/core/thread/Stop-IcingaThread.psm1
  lib/daemon/Add-IcingaForWindowsDaemon.psm1
  lib/daemon/Set-IcingaForWindowsThreadAlive.psm1
  lib/daemon/Suspend-IcingaForWindowsFrozenThreads.psm1
  lib/daemons/RestAPI/threads/Get-IcingaNextRESTApiThreadId.psm1
  lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
  lib/daemons/RestAPI/threads/Start-IcingaForWindowsRESTThread.psm1
Labels: Enhancement, cla/signed

#501 Doc: Updates IWKB for perf lib errors
  doc/knowledgebase/IWKB000008.md
Labels: Documentation

#497 Use a BlockingCollection to avoid busy loop in REST API threads
  doc/100-General/10-Changelog.md
  lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
  lib/daemons/RestAPI/daemon/Start-IcingaWindowsRESTApi.psm1
  lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
Labels: cla/signed
