Repository Icinga/icinga-powershell-framework, pull requests merged in 2023-11, with the labels that each got.

#661 Fix: MsiExec should not cause automatic host reboot
  doc/100-General/10-Changelog.md
  lib/core/icingaagent/installer/Install-IcingaAgent.psm1
  lib/core/icingaagent/installer/Uninstall-IcingaAgent.psm1
  lib/core/repository/Install-IcingaComponent.psm1
Labels: Bug, cla/signed

#667 Fix: JEA installer not including REST-Api on first run
  doc/100-General/10-Changelog.md
  lib/core/installer/Start-IcingaForWindowsInstallation.psm1
Labels: Bug, cla/signed

#668 Get-IcingaCheckCommandConfig: improve -IcingaConfig documentation
  doc/200-Icinga-Integration/04-Icinga-Config.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Documentation, cla/signed

#671 Fix: Update compatibility with Icinga for Windows v1.11.0
  lib/core/repository/Install-IcingaComponent.psm1
  lib/core/repository/Update-Icinga.psm1
Labels: Enhancement, cla/signed
