Repository Icinga/icinga-powershell-framework, pull requests merged in 2023-07, with the labels that each got.

#635 Feature: Adds support to allow Agent cipher list configuration
  doc/100-General/10-Changelog.md
  lib/core/icingaagent/writers/Write-IcingaAgentApiConfig.psm1
Labels: Enhancement, cla/signed

#641 Feature: Adds support to ignore SSL errors on IMC, Shell and Installer
  doc/100-General/10-Changelog.md
  icinga-powershell-framework.psm1
  lib/core/installer/Install-Icinga.psm1
Labels: Enhancement, cla/signed

#642 Feature: Adds support to configure Director Self-Service config string
  doc/100-General/10-Changelog.md
  lib/apis/Register-IcingaDirectorSelfServiceHost.psm1
  lib/core/installer/Install-Icinga.psm1
  lib/core/installer/menu/installation/AdvancedEntries.psm1
  lib/core/installer/menu/installation/director/SelfServiceConfig.psm1
  lib/core/installer/tools/CustomConfig.psm1
  lib/core/installer/tools/SetValuesFromStep.psm1
Labels: Enhancement, cla/signed

#643 Feature: Adds support for -RebuildCache flag on icinga cmd to rebuild component cache
  doc/100-General/10-Changelog.md
  icinga-powershell-framework.psm1
Labels: Enhancement, cla/signed

#644 Feature: Adds progress bar to repository interaction instead of text output
  doc/100-General/10-Changelog.md
  lib/core/repository/New-IcingaRepository.psm1
  lib/core/repository/New-IcingaRepositoryFile.psm1
  lib/core/repository/Sync-IcingaRepository.psm1
  lib/core/repository/Update-IcingaRepository.psm1
Labels: Enhancement, cla/signed

#645 Fix: Error and exception handling over API checks
  doc/100-General/10-Changelog.md
  lib/daemons/modules/ApiChecks/Invoke-IcingaApiChecksRESTCall.psm1
  lib/icinga/exception/Exit-IcingaThrowException.psm1
Labels: Bug, cla/signed

#633 Get-IcingaCheckCommandConfig: provide vars.ifw_api_arguments in each command
  doc/100-General/10-Changelog.md
  doc/110-Installation/30-API-Check-Forwarder.md
  doc/300-Knowledge-Base.md
  doc/images/04_knowledgebase/IWKB000015/01_stringescape.png
  doc/images/04_knowledgebase/IWKB000015/02_stringescaped_correctly.png
  doc/images/05_installation/02_ifw-api/01_powershell_base.png
  doc/knowledgebase/IWKB000015.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: cla/signed

#646 Fix: REST-Api to allow args with and without leading -
  doc/100-General/10-Changelog.md
  lib/daemons/modules/ApiChecks/Invoke-IcingaApiChecksRESTCall.psm1
Labels: Bug, cla/signed

#647 Feature: Improves error/exception handling
  lib/icinga/exception/Exit-IcingaThrowCritical.psm1
  lib/icinga/exception/Exit-IcingaThrowException.psm1
Labels: Enhancement, cla/signed

#648 Fix: Improves REST-Api memory management
  doc/100-General/10-Changelog.md
  lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
  lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
  lib/daemons/modules/ApiChecks/Invoke-IcingaApiChecksRESTCall.psm1
Labels: Bug, cla/signed

#637 Feature: Adds new plugin data provider handling and cpu data
  doc/100-General/10-Changelog.md
  lib/core/tools/Test-IcingaForWindowsCmdletLoader.psm1
  lib/provider/assets/cpu/Get-IcingaProviderDataValuesCpu.psm1
  lib/provider/core/Get-IcingaProviderData.psm1
  lib/provider/core/Get-IcingaProviderElement.psm1
  lib/provider/core/New-IcingaProviderObject.psm1
Labels: Enhancement, cla/signed

#650 Feature: Adds support to not load a new PowerShell instance for command icinga
  doc/100-General/10-Changelog.md
  icinga-powershell-framework.psm1
Labels: Enhancement, cla/signed

#651 Feature: Adds support to write the name of the repo inside the json file
  doc/100-General/10-Changelog.md
  lib/core/repository/New-IcingaRepositoryFile.psm1
  lib/core/repository/Sync-IcingaRepository.psm1
Labels: Enhancement, cla/signed

#652 Fix: Config generator custom variable too long error message
  doc/100-General/10-Changelog.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Enhancement, cla/signed

#638 Feature: Adds option for formatted, colored console prints
  doc/100-General/10-Changelog.md
  lib/core/tools/Write-ColoredOutput.psm1
Labels: cla/signed

#653 Docs: Improves API forwarder documentation
  doc/110-Installation/30-API-Check-Forwarder.md
Labels: Documentation, cla/signed

#654 Fix: Sync-IcingaRepository not saving SSH settings
  doc/100-General/10-Changelog.md
  lib/core/repository/Sync-IcingaRepository.psm1
Labels: Bug, cla/signed

#630 Get-IcingaCheckCommandConfig: set vars.ifw_api_command in all commands
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: cla/signed

#585 Fix typo in 01-JEA-Profiles.md
  doc/130-JEA/01-JEA-Profiles.md
Labels: cla/signed

#613 added -Version parameter to the Update-Icinga` command
  doc/100-General/10-Changelog.md
  doc/111-Updates-and-Uninstallation/01-Update-Environment.md
  lib/core/repository/Update-Icinga.psm1
Labels: cla/signed

#655 Feature: Adds IWKB and test/manage Cmdlets for SCOM intercept counters
  doc/100-General/10-Changelog.md
  doc/300-Knowledge-Base.md
  doc/knowledgebase/IWKB000016.md
  lib/core/health/interceptcounter/Disable-IcingaInterceptCounter.psm1
  lib/core/health/interceptcounter/Enable-IcingaInterceptCounter.psm1
  lib/core/health/interceptcounter/Test-IcingaInterceptCounter.psm1
Labels: Enhancement, Documentation, cla/signed

#656 Feature: Adds new feature to write documents easier
  doc/100-General/10-Changelog.md
  lib/core/docs/Add-IcingaDocumentContent.psm1
  lib/core/docs/New-IcingaDocumentObject.psm1
  lib/core/docs/Write-IcingaDocumentFile.psm1
  lib/core/framework/New-IcingaEnvironmentVariable.psm1
  lib/core/framework/Publish-IcingaPluginDocumentation.psm1
Labels: Enhancement, cla/signed
