Repository Icinga/icinga-powershell-framework, pull requests merged in 2024-08, with the labels that each got.

#735 Feature: Adds support for Acknowledgement events
  doc/100-General/10-Changelog.md
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
  lib/provider/logging/Get-IcingaProviderDataValuesEventlog.psm1
  lib/provider/logging/New-IcingaProviderFilterDataEventlog.psm1
Labels: Enhancement, cla/signed

#742 Feature: Adds option to CPU provider to limit thread usage to 100%
  doc/100-General/10-Changelog.md
  lib/provider/assets/cpu/Get-IcingaProviderDataValuesCpu.psm1
  lib/provider/assets/cpu/New-IcingaProviderFilterDataCpu.psm1
Labels: Enhancement, cla/signed

#740 Feature: Adds support to authenticate with the Icinga for Windows certificate for the REST-Api
  doc/100-General/10-Changelog.md
  jobs/RenewCertificate.ps1
  lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
  lib/core/icingaagent/tests/Test-IcingaForWindows.psm1
  lib/core/logging/Icinga_EventLog_Enums.psm1
  lib/webserver/Import-IcingaCAToAuthRoot.psm1
  lib/webserver/Invoke-IcingaForWindowsRESTApi.psm1
  lib/webserver/Test-IcingaCAInstalledToAuthRoot.psm1
  lib/webserver/Test-IcingaForWindowsCertificate.psm1
Labels: Enhancement, cla/signed

#739 Feature: Adds support to check encoding of files
  doc/100-General/10-Changelog.md
  lib/core/installer/tools/Get-FileEncoding.psm1
  lib/core/tools/Read-IcingaFileSecure.psm1
Labels: Enhancement, cla/signed

#744 Feature: Adds cmdlet `Write-IcingaAgentEventLogConfig` to update eventlog severity and defaults to `warning`during installation and migration
  doc/100-General/10-Changelog.md
  lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
  lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
  lib/core/icingaagent/writers/Write-IcingaAgentEventLogConfig.psm1
  lib/core/installer/Start-IcingaForWindowsInstallation.psm1
Labels: Enhancement, cla/signed

#745 Fix: Service provider for brackets in service names
  doc/100-General/10-Changelog.md
  lib/core/tools/Get-IcingaServices.psm1
  lib/core/tools/Test-IcingaArrayFilter.psm1
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Labels: Bug, cla/signed

#748 Doc: Adds IWKB000019 for RegexErrors
  doc/300-Knowledge-Base.md
  doc/knowledgebase/IWKB000019.md
Labels: Documentation, cla/signed

#743 REST API: in the Server header, identify the software, not the machine
  doc/100-General/10-Changelog.md
  lib/webserver/New-IcingaTCPClientRESTMessage.psm1
Labels: Bug, cla/signed

#750 Rework: Plugin and checker core handling for plugin evaluation
  doc/100-General/10-Changelog.md
  lib/core/framework/Get-IcingaCheckSchedulerPerfData.psm1
  lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
  lib/core/framework/New-IcingaEnvironmentVariable.psm1
  lib/core/tools/Convert-IcingaPluginThresholds.psm1
  lib/core/tools/Convert-IcingaPluginValueToString.psm1
  lib/icinga/enums/Icinga_IcingaEnums.psm1
  lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
  lib/icinga/plugin/Compare-IcingaPluginValueToThreshold.psm1
  lib/icinga/plugin/Convert-IcingaPluginThresholdsFromPercent.psm1
  lib/icinga/plugin/New-IcingaCheck.psm1
  lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
  lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
  lib/icinga/plugin/Write-IcingaPluginResult.psm1
Labels: Enhancement, cla/signed

#747 Fix: Performance counter results sometimes reporting null instead of 0
  doc/100-General/10-Changelog.md
  lib/core/perfcounter/New-IcingaPerformanceCounterObject.psm1
  lib/icinga/plugin/New-IcingaCheck.psm1
Labels: Bug, cla/signed
