Repository Icinga/icinga-powershell-framework, pull requests merged in 2024-03, with the labels that each got.

#689 Fix: Icinga CA port handling on installation
  doc/100-General/10-Changelog.md
  lib/core/icingaagent/installer/Install-IcingaAgentCertificates.psm1
  lib/core/installer/Start-IcingaForWindowsInstallation.psm1
Labels: cla/signed

#688 Feature: Adds handling to add scheduled task background task
  doc/100-General/10-Changelog.md
  jobs/GetWindowsService.ps1
  jobs/RenewCertificate.ps1
  jobs/RestartWindowsService.ps1
  jobs/StartWindowsService.ps1
  jobs/StopWindowsService.ps1
  lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
  lib/core/framework/Uninstall-IcingaForWindows.psm1
  lib/core/installer/Start-IcingaForWindowsInstallation.psm1
  lib/core/wintasks/Invoke-IcingaWindowsScheduledTask.psm1
  lib/core/wintasks/Invoke-IcingaWindowsServiceHandlerTask.psm1
  lib/core/wintasks/Wait-IcingaWindowsScheduledTask.psm1
  lib/core/wintasks/daemon/Register-TaskRenewCertificate.psm1
  lib/core/wintasks/daemon/Start-TaskRenewCertificate.psm1
  lib/core/wintasks/daemon/Unregister-TaskRenewCertificate.psm1
Labels: Bug, cla/signed

#631 Get-IcingaCheckCommandConfig: move -C from every single command to template
  doc/100-General/10-Changelog.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: cla/signed

#690 Feature: Adds renewal handling for Icinga for Windows certificate
  doc/100-General/10-Changelog.md
  lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
  lib/core/installer/Start-IcingaForWindowsInstallation.psm1
  lib/core/installer/menu/manage/framework/ToogleFrameworkApiChecks.psm1
  lib/core/jea/Install-IcingaJeaProfile.psm1
  lib/core/wintasks/daemon/Register-TaskRenewCertificate.psm1
  lib/daemon/Start-IcingaPowerShellDaemon.psm1
  lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
  lib/daemons/RestAPI/eventlog/Register-IcingaEventLogMessagesRESTApi.psm1
  lib/daemons/RestAPI/threads/New-IcingaForWindowsCertificateThreadTaskInstance.psm1
  lib/daemons/RestAPI/threads/Start-IcingaForWindowsCertificateThreadTask.psm1
Labels: Enhancement, cla/signed

#669 Sum up TotalLoad over all CPUs and divide it by number of threads
  doc/100-General/10-Changelog.md
  lib/provider/assets/cpu/Get-IcingaProviderDataValuesCpu.psm1
Labels: Bug, cla/signed

#692 Feature: Renames "Restart-IcingaWindowsService" to "Restart-IcingaForWindows" and adds alias for backwards compatibility
  doc/100-General/01-Upgrading.md
  doc/100-General/10-Changelog.md
  doc/100-General/20-Eventlog.md
  doc/110-Installation/05-Background-Daemons.md
  doc/110-Installation/06-Collect-Metrics-over-Time.md
  doc/110-Installation/30-API-Check-Forwarder.md
  doc/900-Developer-Guide/10-Custom-Daemons.md
  doc/900-Developer-Guide/12-Custom-API-Endpoints.md
  doc/knowledgebase/IWKB000005.md
  doc/knowledgebase/IWKB000014.md
  lib/core/framework/Install-IcingaForWindowsService.psm1
  lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
  lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
  lib/core/installer/Start-IcingaForWindowsInstallation.psm1
  lib/core/installer/menu/manage/framework/ToogleFrameworkApiChecks.psm1
  lib/core/installer/menu/manage/settings/services/ManageServices.psm1
  lib/core/logging/Icinga_EventLog_Enums.psm1
  lib/core/repository/Update-Icinga.psm1
  lib/core/windows/Install-IcingaSecurity.psm1
  lib/core/windows/Install-IcingaServiceUser.psm1
  lib/core/windows/Restart-IcingaWindowsService.psm1
  lib/core/windows/Uninstall-IcingaServiceUser.psm1
  lib/core/windows/Update-IcingaServiceUser.psm1
  lib/core/wintasks/Invoke-IcingaWindowsScheduledTask.psm1
Labels: Enhancement, cla/signed

#693 Feature: Adds new command `Restart-Icinga` to restart both, the Icinga Agent and Icinga for Windows
  doc/100-General/10-Changelog.md
  lib/core/windows/Restart-Icinga.psm1
Labels: Enhancement, cla/signed

#694 Feature: Adds support for check objects not being added to summary header
  doc/100-General/10-Changelog.md
  lib/icinga/plugin/New-IcingaCheck.psm1
  lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
Labels: Enhancement, cla/signed

#682 Feature: Adds new Eventlog data provider
  doc/100-General/10-Changelog.md
  lib/provider/core/Get-IcingaProviderFilterData.psm1
  lib/provider/core/New-IcingaProviderFilterObject.psm1
  lib/provider/logging/Add-IcingaProviderEventlogFilterData.psm1
  lib/provider/logging/Get-IcingaProviderDataValuesEventlog.psm1
  lib/provider/logging/New-IcingaProviderFilterDataEventlog.psm1
Labels: Bug, Enhancement, cla/signed

#695 Feature: Adds security hardening to JEA profiles by always prohibit certain cmdlets
  doc/100-General/10-Changelog.md
  doc/110-Installation/02-Icinga-Management-Console.md
  doc/110-Installation/03-Installation-with-IMC.md
  icinga-powershell-framework.psd1
  lib/core/jea/Deny-IcingaJEACommand.psm1
  lib/core/jea/Get-IcingaCommandDependency.psm1
  lib/core/jea/Get-IcingaFrameworkDependency.psm1
  lib/core/jea/Get-IcingaJEAConfiguration.psm1
  lib/core/jea/Read-IcingaPowerShellModuleFile.psm1
  templates/IcingaForWindows.psrc.template
Labels: Security, cla/signed

#697 Docs: Adds IWKB entry `IWKB000017` handling issues with failed checks once SCOM is uninstalled
  doc/100-General/10-Changelog.md
  doc/300-Knowledge-Base.md
  doc/knowledgebase/IWKB000017.md
Labels: Documentation, cla/signed

#700 Feature: Adds support to use pipes and multi lines for plugin documentation
  doc/100-General/10-Changelog.md
  lib/core/framework/Publish-IcingaPluginDocumentation.psm1
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Enhancement, Documentation, cla/signed

#702 Fix: Icinga Director Self-Service API is ignoring service user
  doc/100-General/10-Changelog.md
  lib/core/installer/menu/installation/director/DirectorTemplate.psm1
Labels: Bug, cla/signed

#707 Fix: Size of Icinga for Windows eventlog
  doc/100-General/10-Changelog.md
  lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
  lib/core/logging/Register-IcingaEventLog.psm1
Labels: cla/signed
