Repository Icinga/icinga-powershell-framework, pull requests merged in 2025-01, with the labels that each got.

#759 Set maximum cache duration for service daemons to the right value
  doc/100-General/10-Changelog.md
  lib/daemons/ServiceCheckDaemon/tools/New-IcingaServiceCheckDaemonEnvironment.psm1
Labels: Bug, cla/signed

#772 Feature: Adds new Metric over Time handling
  doc/100-General/10-Changelog.md
  lib/core/framework/New-IcingaEnvironmentVariable.psm1
  lib/daemons/ServiceCheckDaemon/task/Add-IcingaServiceCheckTask.psm1
  lib/daemons/ServiceCheckDaemon/tools/New-IcingaServiceCheckDaemonEnvironment.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
  lib/icinga/plugin/Compare-IcingaPluginValueToThreshold.psm1
  lib/icinga/plugin/ConvertTo-IcingaMetricsOverTime.psm1
  lib/icinga/plugin/Get-IcingaMetricsOverTimePerfData.psm1
  lib/icinga/plugin/New-IcingaCheck.psm1
  lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
  lib/icinga/plugin/New-IcingaCheckResult.psm1
  lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
Labels: Enhancement, cla/signed

#774 Fix: Passwords being written as plain text in EventLog on error
  doc/100-General/10-Changelog.md
  lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
Labels: Security, cla/signed

#775 Feature: Improves service recover by adjustable restart time interval argument
  doc/100-General/10-Changelog.md
  lib/core/windows/Enable-IcingaServiceRecovery.psm1
Labels: Enhancement, cla/signed

#751 Update GetWindowsService.ps1
  jobs/GetWindowsService.ps1
Labels: cla/signed

#777 Fix: Docs creation for MoT handling with -ThresholdInterval argument
  lib/core/framework/Publish-IcingaPluginDocumentation.psm1
Labels: Enhancement, Documentation, cla/signed

#779 Fix: Test commands failing because wrong assigned service data
  doc/100-General/10-Changelog.md
  jobs/GetWindowsService.ps1
Labels: Bug, cla/signed
