Repository Icinga/icinga-powershell-framework, pull requests merged in 2025-04, with the labels that each got.

#801 Docs: Updates documentation
  doc/000-Introduction.md
  doc/100-General/01-Upgrading.md
  doc/100-General/10-Changelog.md
  doc/110-Installation/30-API-Check-Forwarder.md
  doc/900-Developer-Guide/12-Custom-API-Endpoints.md
  doc/images/02_icons/iis.png
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Documentation, cla/signed

#802 Change broken icinga.com/blog links to GitHub release links
  doc/100-General/90-Roadmap.md
Labels: cla/signed

#799 Fix: Wrong performance data values on unit conversion
  doc/100-General/10-Changelog.md
  lib/core/tools/ConvertTo-IcingaUnixTime.psm1
  lib/core/tools/Get-IcingaUnixTimeOffsetNow.psm1
  lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
  lib/icinga/plugin/Compare-IcingaPluginValueToThreshold.psm1
  lib/icinga/plugin/New-IcingaCheck.psm1
Labels: Bug, cla/signed

#803 Fix: UNKNOWN on checks using MoT thresholds if they are newly registered
  doc/100-General/10-Changelog.md
  lib/daemons/ServiceCheckDaemon/task/Add-IcingaServiceCheckTask.psm1
Labels: Bug, cla/signed

#804 Fix: Icinga for Windows freezing on empty config.json
  cache/framework_cache.psm1
  doc/100-General/10-Changelog.md
  lib/core/installer/tools/Get-FileEncoding.psm1
Labels: Bug, cla/signed

#805 Fix: Icinga for Windows installer to always force service installation
  doc/100-General/10-Changelog.md
  lib/core/installer/Start-IcingaForWindowsInstallation.psm1
Labels: Bug, cla/signed

#806 Fix: Threshold comparison to only apply for ranged values
  doc/100-General/10-Changelog.md
  lib/icinga/plugin/New-IcingaCheck.psm1
Labels: Bug, cla/signed

#807 Fix: Icinga for Windows being stuck while fetching service information if other services block CIM requests
  doc/100-General/10-Changelog.md
  lib/core/tools/Get-IcingaServices.psm1
Labels: cla/signed

#808 Fix: Config compiler to always use Switchparameter for switch argument
  doc/100-General/10-Changelog.md
  lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Labels: Bug, cla/signed

#810 Feature: Adds support to suppress messages for Disable-IcingaUntrustedCertificateValidation
  doc/100-General/10-Changelog.md
  lib/webserver/Disable-IcingaUntrustedCertificateValidation.psm1
Labels: Enhancement, cla/signed

#811 Fix: AddSummaryHeader not adding any check information to check package
  doc/100-General/10-Changelog.md
  lib/icinga/plugin/New-IcingaCheckPackage.psm1
Labels: Bug, cla/signed
